# Generated by Django 2.2.1 on 2019-05-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_total_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(auto_created=True, verbose_name='发布时间'),
        ),
    ]
